
    create table tb_category (
       id bigint generated by default as identity,
        created_at TIMESTAMP WITHOUT TIME ZONE,
        name varchar(255),
        updated_at TIMESTAMP WITHOUT TIME ZONE,
        primary key (id)
    );

    create table tb_product (
       id bigint generated by default as identity,
        date TIMESTAMP WITHOUT TIME ZONE,
        description TEXT,
        img_url varchar(255),
        name varchar(255),
        price double,
        primary key (id)
    );

    create table tb_product_category (
       product_id bigint not null,
        category_id bigint not null,
        primary key (product_id, category_id)
    );

    create table tb_role (
       id bigint generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table tb_state (
       id bigint generated by default as identity,
        state_abbreviation varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table tb_user (
       id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(20),
        last_name varchar(20),
        password varchar(20),
        primary key (id)
    );

    create table tb_user_role (
       user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    alter table tb_user 
       add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);

    alter table tb_product_category 
       add constraint FK5r4sbavb4nkd9xpl0f095qs2a 
       foreign key (category_id) 
       references tb_category;

    alter table tb_product_category 
       add constraint FKgbof0jclmaf8wn2alsoexxq3u 
       foreign key (product_id) 
       references tb_product;

    alter table tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;

